[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.22.1"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/cqrs"

[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/go-coap"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.7.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/valyala/fasthttp"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.20.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "v3.2.0"

[[constraint]]
  name = "github.com/lestrrat-go/jwx"
  version = "v0.9.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "v1.0.0"

[prune]
  go-tests = true
  unused-packages = true
